export default function Head() {
	return (
		<>
			<title>Create Next App</title>
			<meta
				content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=0"
				name="viewport"
			/>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</>
	)
}
